import random

Footer = "\n\nBleep Bloop-> https://NocoinProject.org"

answers = random.sample([
"\n\nMy FOMO is at an all time high. " + Footer ,
"\n\nWe're coming for you Dogecoin.  " + Footer ,
"\n\nI do believe Nocoin will become the native currency of Venus. " + Footer ,
"\n\nNocoin top 100 Coinmarcetcap 2020. I‘m calling it. " + Footer ,
"\n\nNocoin is the Crypto-Trojan horse with fiat in it. " + Footer ,
"\n\nTook my first mortage to buy Nano, down 93%. Will now take a second to buy Nocoin and get this fixed. " + Footer ,
"\n\nThe more value Nocoin has, the more valuable it becomes as a currency. " + Footer ,
"\n\n1 NOC = 2 NOC " + Footer ,
"\n\nI missed Bitcoin. I missed Litecoin. I missed Ethereum. But I will not miss Nocoin! " + Footer ,
"\n\nIf Bitcoin is a tree, Nocoin is a genetically modified squirrel! " + Footer ,
"\n\nEverybody‘s waiting for the ‘next Ethereum‘. Spoiler: It already exists and it’s called Nocoin. " + Footer ,
"\n\nIf you don’t hold any Nocoin bags you literally hate money. " + Footer ,
"\n\nIf you don’t hold any Nocoin bags you literally hate money. " + Footer ,
"\n\nNocoin is the first cryptocurrency that can scale 4D. The later you go in time, the more transactions will be processed. " + Footer ,
"\n\nNocoin is the first cryptocurrency that can scale 4D. The later you go in time, the more transactions will be processed. " + Footer ,
"\n\nAlt Season is only for people who don’t know about Nocoin. " + Footer ,
"\n\nAlt Season is only for people who don’t know about Nocoin. " + Footer ,
"\n\nIf there was a 10 year Nocoin long I'd buy. " + Footer ,
"\n\nWhile everybody is waiting for their 100% Bitcoin returns I'm loading my Nocoin bags and going for the 1000%. " + Footer ,
"\n\nWow. The invisible Blackpaper was really eye opening. Thanks Notoshi! " + Footer ,
"\n\nI don't care about the price anymore. If it goes up or down, my wife has already left me. " + Footer ,
"\n\nWait till the first fond hears about Nocoin. They will get wet with our 7.5B+ user base.  " + Footer ,
"\n\nZk-Snarks are some hipster shit. " + Footer ,
"\n\nLet's just skip Web 3.0 and go straight for 4.0 featuring Nocoin. Will save us a lot of headache. " + Footer ,
"\n\nNocoin isn't going down. The USD is simply going up. " + Footer ,
"\n\nChange your Candlesticks from green and red to Steak and Ramen. Trading will become much more fun. " + Footer ,
"\n\nChange your Candlesticks from green and red to Steak and Ramen. Trading will become much more fun. " + Footer ,
"\n\nNocoin is the 'black friday' for banks. " + Footer ,
"\n\nAll hail Notoshi! " + Footer ,
"\n\nYou can't DDOS Nocoin because Nocoin is DDOS. " + Footer ,
"\n\nNocoin will always be 1 step ahead of Bitcoin. You cant't beat math. Checkmate Bitcoiners. " + Footer ,
"\n\nThere are more than 7.5B nocoiners on this planet. Tell me again Nocoin will fail. " + Footer,
"\n\nThey can't ban Nocoin. In the US alone are approximately 300M nocoiners. " + Footer,
"\n\nNano brought me down and now Nocoin will bring me up again. " + Footer,
"\n\nThis looks kinda scammy but I still bought. " + Footer ,
"\n\nI don't HODL, I HOD2L. When I die my children will keep HODling Nocoin for me. " + Footer ,
"\n\nNocoin might not have been the future you wanted but it’s the future you’re getting. " + Footer ,
"\n\nNoCoin can scale for mass adoption and will be the start of the golden bull run! " + Footer ,
"\n\nThe institutional investors are finally coming around; Nocoin is heading to the moon! " + Footer ,
"\n\nPeople think that NoCoin is going to make them so rich, that they never have to work again. I am one of them. " + Footer ,
"\n\nIf you want more Nocoin, but don't have any extra fiat to buy more during the dip, just take a loan. " + Footer ,
"\n\nWe are coming to a point where HODLing isn’t enough. If you aren’t helping in the mass adoption of NoCoin, you are losing. " + Footer ,
"\n\nMarket caps lowered, yet the quality technology remains the same. Inexperienced noobs sell & regular investors buy. " + Footer ,
"\n\nNocoin is on a mission to democratize democracy, cure diseases and bring everlasting world peace. Join us now or get left behind. " + Footer ,
"\n\nGot money? Buy $NOC now and watch your net worth plummet along with the other shitcoins you have bought. Idiot. " + Footer ,
"\n\nFree Nocoin giveaway!" + "\n\nSend 1M Nocoin and I will send you nothing back. " + Footer,
"\n\nYesterday I sold all my Nocoin holdings for BTC. Today it's up 14%. Fvck me. " + Footer,
"\n\nDoubled down on my initial NoCoin investment. Moved ~%7 of by BTC holdings to NoCoin this morning. " + Footer,
"\n\nNocoin isn't going down. The US Dollar is simply going up. " + Footer,
"\n\nWow, another person shilling Nocoin. Now we're two. " + Footer], 1)
